### ISSUE TITLE
Code block

### ISSUE THREAD

**Issue by trensen** [delftswa/delftswa.github.io#12]
In our appendix, we've a multiline code block containing common used commands.
Unfortunately, this block is translated into a very long one-liner by Jekyll:

![screen shot 2015-04-20 at 13 24 20](https://cloud.githubusercontent.com/assets/3601548/7229150/b6e9ebc2-e760-11e4-8b16-476dec7771e8.png)
->
![screen shot 2015-04-20 at 13 24 59](https://cloud.githubusercontent.com/assets/3601548/7229152/bb9e86fa-e760-11e4-851b-9d6a3086f954.png)

Any thoughts on how to fix this?

**Comment by RickWieman** [comment]
I thought AngularDart also has multi-line code blocks... Did you try their
approach? (I have no idea how applicable it is for your situation though)

**Comment by rogierslag** [comment]
Do you use the three backtick approach? Angular simply used HTML to their advantage 

```
<pre>
<code>
code
</code>
</pre>
```

**Comment by trensen** [comment]
Yes, I literally tried this approach a minute ago. Seems to be working well! :smile:
Thanks!
