### ISSUE TITLE
Measure page views

### ISSUE THREAD

**Issue by avandeursen** [delftswa/delftswa.github.io#15]
It would be nice to see how well the book is read.

Configure Google Analytics so that it shows us page views for each chapter?

**Comment by rogierslag** [comment]
Do you want more info than just what Github provides? https://github.com/blog/1672-introducing-github-traffic-analytics

**Comment by avandeursen** [comment]
GitHub traffic analytics is for repositories, not for GitHub pages, if I'm not mistaken.

**Comment by rogierslag** [comment]
#neverTrustBlogs

I will integrate it asap!

**Comment by RickWieman** [comment]
Fixed by #24 ?

**Comment by rogierslag** [comment]
Certainly is!
