### ISSUE TITLE
Add a publishing date to the website

### ISSUE THREAD

**Issue by rogierslag** [delftswa/delftswa.github.io#23]
In general, most of the software treated here is quite stable. However some package (e.g. Docker or Tribler) have some big changes coming up. Once this book is indexed by Google as well, this might cause people to believe that the (at some point) outdated information is still current. I'd therefore like to add a date to each chapter when it was published in order to give people some clue how old the information is.

When we think about the future years, this is more pressing. In 2016, some projects on the site might only be a month old, whereas the 2015 edition will be over a year old (unless updated).

@avandeursen what do you think of this?

Also tagging the current chapter generators: @thegeman @JoopAue @trensen @RickWieman @S-Ercan @Donenzone @hermanbanken

**Comment by gewoonrik** [comment]
I agree, our chapter is now already somewhat outdated

**Comment by RickWieman** [comment]
The introduction (#19) does mention the course took place in the spring of 2015, but I agree that might be a little bit thin. Perhaps we should add a publication date (i.e., the date of the last modification of the content (might vary per team)) to the headers of the chapters?
