### ISSUE TITLE
Kodi appendix not working correctly

### ISSUE THREAD

**Issue by kajdreef** [delftswa/delftswa.github.io#25]
@rogierslag @avandeursen we (team-kodi) also created an appendix and added that to the repository ([link](http://delftswa.github.io/chapters/kodi/appendix.md)) but as you can see upon opening it you don't get a nice webpage. 

Should I also add a YAML to this page as well? And should the format be different because I assume the appendix should not show up in the table of content?

**Comment by rogierslag** [comment]
Yup you need YAML front page matter to ensure github renders it!

**Comment by rogierslag** [comment]
Seems to work now, but you have link to http://delftswa.github.io/chapters/kodi/appendix.html

Also I see some HTML in the generated html. Can you check whether this is correct?
